---
- name: "Automate Docker Build using Ansible"
  hosts: localhost
  tasks:
  - name: stop running container 
    command: docker stop django-container 
    ignore_errors: yes

  - name: remove stopped container 
    command: docker rm django-container
    ignore_errors: yes

  - name: remove used image 
    command: docker rmi appgain/survey-app-img
    ignore_errors: yes

  - name: build new image 
    command: docker build -t appgain/survey-app-img .

  - name: push docker image  
    command: docker push appgain/survey-app-img
